{-
   
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.HappyHour exposing (HappyHour, happyHourDecoder, happyHourEncoder)

import Data.Schedule exposing (Schedule, scheduleDecoder, scheduleEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias HappyHour =
    { city : String
    , restaurant : String
    , schedule : (List Schedule)
    , link : String
    }


happyHourDecoder : Decoder HappyHour
happyHourDecoder =
    decode HappyHour
        |> required "city" Decode.string
        |> required "restaurant" Decode.string
        |> required "schedule" (Decode.list scheduleDecoder)
        |> required "link" Decode.string



happyHourEncoder : HappyHour -> Encode.Value
happyHourEncoder model =
    Encode.object
        [ ( "city", Encode.string model.city )
        , ( "restaurant", Encode.string model.restaurant )
        , ( "schedule", (Encode.list << List.map scheduleEncoder) model.schedule )
        , ( "link", Encode.string model.link )
        ]


