{-
   
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.Schedule exposing (Schedule, scheduleDecoder, scheduleEncoder)

import Data.DayOfWeek exposing (DayOfWeek, dayOfWeekDecoder, dayOfWeekEncoder)
import Data.TimeRange exposing (TimeRange, timeRangeDecoder, timeRangeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias Schedule =
    { days : (List DayOfWeek)
    , time : TimeRange
    , scheduleDescription : String
    }


scheduleDecoder : Decoder Schedule
scheduleDecoder =
    decode Schedule
        |> required "days" (Decode.list dayOfWeekDecoder)
        |> required "time" timeRangeDecoder
        |> required "scheduleDescription" Decode.string



scheduleEncoder : Schedule -> Encode.Value
scheduleEncoder model =
    Encode.object
        [ ( "days", (Encode.list << List.map dayOfWeekEncoder) model.days )
        , ( "time", timeRangeEncoder model.time )
        , ( "scheduleDescription", Encode.string model.scheduleDescription )
        ]


