{-
   
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.TimeRange exposing (TimeRange, timeRangeDecoder, timeRangeEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias TimeRange
    = String


timeRangeDecoder : Decoder TimeRange
timeRangeDecoder =
    Decode.string


timeRangeEncoder : TimeRange -> Encode.Value
timeRangeEncoder =
    Encode.string
